import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "React two finger pan zoom and pinch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-svh">
      <body className="h-full">{children}</body>
    </html>
  );
}
